export const USER_ROLES = [
  "REFERRING_VET",
  "RECEIVING_CLINICIAN",
  "OWNER",
  "ORGANISATION_ADMIN",
] as const;

export type UserRole = (typeof USER_ROLES)[number];

export const REFERRAL_TRANSITION_ROLES: Partial<
  Record<string, readonly UserRole[]>
> = {
  READY_FOR_REVIEW: ["REFERRING_VET"],
  SUBMITTED: ["REFERRING_VET"],
  MORE_INFORMATION_REQUIRED: ["RECEIVING_CLINICIAN"],
  ACCEPTED: ["RECEIVING_CLINICIAN"],
  APPOINTMENT_BOOKED: ["RECEIVING_CLINICIAN"],
  ADMITTED: ["RECEIVING_CLINICIAN"],
  TREATMENT_IN_PROGRESS: ["RECEIVING_CLINICIAN"],
  DISCHARGED: ["RECEIVING_CLINICIAN"],
  FOLLOW_UP_ACTIVE: ["RECEIVING_CLINICIAN"],
  CLOSED: ["REFERRING_VET", "RECEIVING_CLINICIAN"],
  DECLINED: ["RECEIVING_CLINICIAN"],
  CANCELLED: ["REFERRING_VET", "RECEIVING_CLINICIAN"],
};
